import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.globaltechanalytics.in/');
  await page.goto('https://admin.globaltechanalytics.in/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('user@example.com');
  await page.locator('.mat-mdc-form-field.w-full.mat-mdc-form-field-type-mat-input.mat-form-field-appearance-outline.mat-primary.ng-untouched.ng-pristine > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('menu').click();
  await page.getByRole('link', { name: 'Task Management' }).click();
  await page.locator('.overlay').click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.locator('ng-select').filter({ hasText: 'Select Level' }).getByRole('combobox').click();
  await page.getByText('State').click();
  await page.locator('div').filter({ hasText: /^Select State$/ }).first().click();
  await page.getByText('Delhi').click();
  await page.locator('ng-select').filter({ hasText: 'Select Role' }).getByRole('combobox').click();
  await page.getByText('Volunteer').click();
  await page.locator('.w-full.relative').first().click();
  await page.getByRole('textbox', { name: 'Enter text...' }).click();
  await page.getByRole('textbox', { name: 'Enter text...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter text...' }).fill('R');
  await page.getByRole('textbox', { name: 'Enter text...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter text...' }).fill('Recording ');
  await page.getByRole('textbox', { name: 'Enter text...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter text...' }).fill('Recording T');
  await page.getByRole('textbox', { name: 'Enter text...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter text...' }).fill('Recording Task');
  await page.locator('.ql-editor').press('CapsLock');
  await page.locator('.ql-editor').click();
  await page.locator('.ql-editor').fill('R');
  await page.locator('.ql-editor').press('CapsLock');
  await page.locator('.ql-editor').fill('Recording ');
  await page.locator('.ql-editor').press('CapsLock');
  await page.locator('.ql-editor').fill('Recording T');
  await page.locator('.ql-editor').press('CapsLock');
  await page.locator('.ql-editor').press('CapsLock');
  await page.locator('.ql-editor').fill('Recording TASK DESCRIPTION');
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('button', { name: 'September 30,' }).click();
  await page.locator('#mat-mdc-dialog-0').click();
  await page.getByRole('textbox', { name: 'hh:mm AM/PM' }).click();
  await page.getByRole('button', { name: '17' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('n');
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('nAME');
  await page.getByRole('button', { name: 'Preview' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('Create a Task Preview Submit').click();
  await page.getByRole('button', { name: 'Submit' }).click();
});